### PR TITLE
Removed TestMenuScript object from these scenes as it's not used and …

### PR DESCRIPTION
**Pull request by snngfds**
…it crashes the scene while looking for "Tutorial" key on the dictionary.

### CODE REVIEW

**Comment by Xerios** [comment]
You're absolutely right. I made those scenes fairly quickly, I must've forgot to test them for more than 5 seconds to actually notice the error :)

Thanks! Will merge immediately.

**Comment by snngfds** [comment]
Yeah I thought you have forgotten to disable the gameobject. I was looking to create something like that I might use this fork as a base. Do you have plans on particular future features? I might help develop those.

**Comment by Xerios** [comment]
I'd love to have some help on this. I recently got a case where I needed use this project again, so I'm gonna be active once again.

No particular features planned yet, but things could definitely be improved in many ways. Like inspector UI is not entirely in sync with the latest changes, like for instance All | Screens | Popups filter doesn't work as intended ( probably because I changed them to Layers instead of two different Screen classes )

**Comment by Xerios** [comment]
Same could be said about better tutorials or examples, because I don't think the current ones display all its features :)

**Comment by snngfds** [comment]
I'll have a look at the whole code base, features and try to improve on the things you mentioned. Cheers.

**Pull request merged**
